### ISSUE TITLE
drive encryption causes mercurial to falsely list modified files

### ISSUE THREAD

**Issue by kristin-jay** [google/fscrypt#112]
I have a mercurial repo in my home directory on Ubuntu 18.04
I followed these steps [http://tlbdk.github.io/ubuntu/2018/10/22/fscrypt.html](url) 
The folder encrypts successfully, however quite frequently now mercurial reports files as modified (via `hg status`) when there are no changes to them. 
Is this a known issue? I couldn't find anything on it in the usual places such as stackoverflow. 
Thanks in advance, and apologies if I've inadvertently breached the usual protocols for raising an issue, it's my first one.

**Comment by josephlr** [comment]
@kristin-jay this is interesting, I'll look into this. However, I would guess this is a kernel issue, as fscrypt merely sets up encryption on a directory, anything to do with individual files is managed directly by the kernel's fs/crypto submodule.

**Comment by josephlr** [comment]
@kristin-jay I was able to get something to show up. Here's what I did. Is the issue you ran into similar?

1. Setup a directory with fscrypt (I used a custom protector)
2. Initialize a mercurial repo in the directory
3. Create a file with some text in it
4. Commit the file
5. Use `fscrypt purge` to clear the keys and lock the directory
6. Now `hg status` is confused about the files.
7. Running `ls` gives that some weird files have been created.
```
drwxr-xr-x 4 joe joe 4.0K Dec  4 15:23 .hg
-rw-r--r-- 1 joe joe    5 Dec  4 15:22 foo
-rw------- 1 joe joe    0 Dec  4 15:46 hg-checkexec-sp_qAD
-rw------- 1 joe joe    0 Dec  4 15:26 hg-checkexec-tLHLw6
```
8. Running `fscrypt unlock` on the directory returns everything to normal.

**Comment by kristin-jay** [comment]
Hi. Apologies for the delay in replying. 
My steps were more like:
1. Setup a directory with fscrypt (using the steps from the URL in my first comment)
2. `hg clone` into the encrypted directory
3. use the directory as per usual, (i.e. create branches, commit changes etc etc)
4. `hg status` shows changes to files that I have not modified

I had a chance to dig a bit more today and it appears to be something to do with softlinked files. The timestamps of softlinks in my hg repo are updating to , and I believe this is why `hg status` is reporting changes.
This problem only started when I encrypted my repo directory,  however I cannot categorically say that it's `fscrypt` that is the source of my problems. 
Thanks for looking into this, but probably best not to look further until I can get a repeatable bunch of steps that show the problem.

**Comment by ebiggers** [comment]
I don't know of any kernel issue that would cause this.  File timestamps work the same regardless of encryption.

Unless more information is given, I think this issue should be closed.
