### ISSUE TITLE
Document `mv` behavior when using filesystem encryption

### ISSUE THREAD

**Issue by josephlr** [google/fscrypt#124]
In #76 @tlbdk brought up issues with using `mv` (i.e. [`rename`](http://man7.org/linux/man-pages/man2/rename.2.html)) with filesystem encryption. We need to:

- [ ] Document this behavior
- [ ] Work with the kernel upstream to figure out what the idea behavior should be. See [Mike Halcrow's proposed patch](https://patchwork.ozlabs.org/cover/811270/
)

To summarize, `rename` either suceeds, returns `EPERM`, or returns `EXDEV` depending on the context. 

|[`rename`](http://man7.org/linux/man-pages/man2/rename.2.html) operation | Current behavior  | Mike's proposed change |
|---|---|---|
| unencrypted -> unencrypted (same filesystem) | Success  | Success |
| unencrypted -> unencrypted (different filesystem) | `EXDEV` | `EXDEV` |
| unencrypted -> encrypted (same filesystem) | `EPERM`  | `EXDEV` |
| unencrypted -> encrypted (different filesystem) | `EXDEV` | `EXDEV` |
| encrypted -> encrypted (same policy) | Success | Success  |
| encrypted -> encrypted (same protector) | `EPERM`  | `EXDEV` |
| encrypted -> encrypted (different policy/protector) | `EPERM`  | `EXDEV` |
| encrypted -> unencrypted (same filesystem) | Success  | Success |

**Comment by tlbdk** [comment]
Hi, not sure how patchwork follows up on merge status, but how is it going with this issue?

**Comment by ebiggers** [comment]
My patch changing EPERM to EXDEV was merged for Linux v5.1-rc1 as https://git.kernel.org/torvalds/c/f5e55e777cc93eae.

**Comment by tlbdk** [comment]
I can confirm that things are working in 5.1, I guess the only thing left is to document this behaviour on older kernels and this issue can be closed.
