### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by pepa65** [google/fscrypt#126]
tag: question
Trying to use fscrypt. Running on Ubuntu 18.04.1 (golang and fscrypt not installed through the standard repos/package manager, but installed libpam0g-dev from the repos).
`go version`: `go1.10.2 linux/amd64`
`uname -rv`: `4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019`
`grep EXT4.*ENCRYPTION /boot/config-4.15.0-44-generic`: CONFIG_EXT4_ENCRYPTION=y CONFIG_EXT4_FS_ENCRYPTION=y

Doing:
```
go get -d github.com/google/fscrypt/...
cd $GOPATH/src/github.com/google/fscrypt
make
sudo make install
sudo pam-auth-update  # Assuming this is necessary
sudo fscrypt setup
sudo mkfs.ext4 /dev/mapper/crypt-os
sudo mount /dev/mapper/crypt-os /mnt
sudo chmod 777 /mnt
fscrypt setup /mnt
mkdir /mnt/crypt
fscrypt encrypt /mnt/crypt/  # This doesn't work...
```
Output:
```
fscrypt encrypt: filesystem /mnt: encryption not enabled

Encryption is either disabled in the kernel config, or needs to be enabled for this filesystem. See the documentation on
how to enable encryption on ext4 systems (and the risks of doing so).
```
I am guessing I am missing a step in 'enabling encryption for this filesystem', but I can't find what. Do you have to adjust a parameter with `tune2fs`?
(If necessary I can submit the output of the other fscrypt commands, but they were all successful.)

**Comment by josephlr** [comment]
@pepa65 your inclination was correct, you [need to enable encryption on your filesystem](https://github.com/google/fscrypt#getting-encryption-not-enabled-on-an-ext4-filesystem). This is in the `README.md` but is all the way at the bottom. 

Long story short, if `/dev/mapper/crypt-os` is EXT4, run:
```bash
sudo tune2fs -O encrypt /dev/mapper/crypt-os
```
you may or may not need to unmount your filesystem for this to work.

You can also enable encryption a filesystem creation time via:
```bash
sudo mkfs.ext4 -O encrypt /dev/mapper/crypt-os
```

**Comment by pepa65** [comment]
Sorry for cluttering up the issues about this! I knew that 'in the past' this had to be manually done, and apparently still.

Might I suggest to put a note under **Example Usage** to look at the very end of the readme, or just suggest `sudo mkfs.ext4 -O encrypt <device>` in that section of the readme?

**Comment by ebiggers** [comment]
> Might I suggest to put a note under Example Usage to look at the very end of the readme, or just suggest sudo mkfs.ext4 -O encrypt <device> in that section of the readme?

https://github.com/google/fscrypt/pull/173 does this.
