### ISSUE TITLE
fscrypt checks wrong device for setup and throws ErrNotSetup

### ISSUE THREAD

**Issue by Redsandro** [google/fscrypt#129]
My `/home` is a separate partition. 

```
$ mount | grep /dev/sd
/dev/sda5 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda6 on /home type ext4 (rw,relatime,data=ordered)
```

I want to test out fscrypt on a test directory.

```
$ sudo fscrypt setup
$ sudo fscrypt setup /home
$ sudo mkdir -p /home/test/enc
$ sudo chown -R redsandro: /home/test
$ sudo fscrypt encrypt /home/test/enc --user=redsandro

Your data can be protected with one of the following sources:
1 - Your login passphrase (pam_passphrase)
2 - A custom passphrase (custom_passphrase)
3 - A raw 256-bit key (raw_key)
Enter the source number for the new protector [2 - custom_passphrase]: 1

fscrypt encrypt: filesystem /: not setup for use with fscrypt

Run "fscrypt setup MOUNTPOINT" to use fscrypt on this filesystem.
```

See: __fscrypt encrypt: filesystem /: not setup for use with fscrypt__

I believe that the state of `/` (AKA `/dev/sda5`) is irrelevant.
This is about `/home` (AKA `/dev/sda6`).

```
$ sudo tune2fs -l /dev/sda6 | grep encrypt
Filesystem features:
    has_journal
    ext_attr
    resize_inode
    dir_index
    filetype
    needs_recovery
    extent
    flex_bg
    encrypt        # <- here it is
    sparse_super
    large_file
    huge_file
    uninit_bg
    dir_nlink
    extra_isize
```

**Comment by Redsandro** [comment]
This seems to work:

```
cd /home/test
sudo fscrypt encrypt enc --user=redsandro
```

I'm not sure if the path from where the command is executed is technically desirable, so I'll leave this issue open.

**Comment by josephlr** [comment]
@Redsandro Thanks for reporting this issue. Your intuition is correct, you should not need to enable encryption on the `/` filesystem to encrypt a directory on the `/home` filesystem. However, when creating a "pam_passphrase" protector (i.e. a protector linked to your login passphrase), fscrypt stores some data on the root partition, specifically a wrapped key that lets your passphrase keep working even if your system password changes.

So the issue shouldn't be the `pwd` but rather the type of protector you are using. I think the best way to solve this would be for `fscrypt setup` (without a mountpoint), to create the necessary files on `/` as well. Note that this does not require `/` to actually support encryption, the metadata files just need to be there to support changing login passwords.
