### ISSUE TITLE
Time for a new pre-release?

### ISSUE THREAD

**Issue by primeos** [google/fscrypt#143]
FYI: The latest release (`0.2.4`) only builds with Go 1.10 and not with more recent major releases of Go. But, according to the [release policy](https://golang.org/doc/devel/release.html#policy),  Go 1.10 was only supported until the release of Go 1.12 on 2019-02-25. Therefore the latest pre-release now depends on an unsupported Go version (AFAIK).

Since support for newer major versions of Go was added in the meantime it might make sense to prepare a new pre-release for downstream maintainers to package.

Feel free to close this issue if you disagree, I just wanted to note it in case this is not intended ;)

**Comment by josephlr** [comment]
Good catch, I will release a new version
