### ISSUE TITLE
Employ fscrypt to securely protect, from data-at-rest exposure, all files+data installed after an initial Linux system build?

### ISSUE THREAD

**Issue by johnnyutahh** [google/fscrypt#155]
**Our team's goal**

We want to protect our sensitive data from being potentially data-at-rest exposed after we relinquish a Linux [VPS][1] (see below) provided by a hosting service. We're exploring simple(r) [fscrypt][2] usage to potentially solve this problem.

We are *_not_* seeking impenetrable, "perfect" security. We're seeking a more (most?) reasonable approach that pragmatically and reliably applies the currently-most-effective industry solution(s).

The following "design" is our first attempt to reach this goal.

**_Is the following accurate, feasible, and reasonable?_**

**Details**

We employ Linux [VPSes][1] to self-host some of our software/services, including from providers [DigitalOcean (DO)][3], [AWS][4], and [GCP][5].  Often these VPSes do not come natively encrypted. They all appear to have [ext4][6]-with-file-based-encryption support, simply because [ext4 has apparently supported Linux filesystem encryption since kernel v4.1][7]. Most of our VPSes currently run [Ubuntu v18.04 LTS, which employs Linux kernel v4.15][8].

We like the [fscrypt][2] concept but are new to its usage and paradigms (to be clear, we are complete [fscrypt][2] newbies). Here's our initial, uneducated run-down of what we're considering and why. In this case we use the DigitalOcean (DO) example. DO calls VPSes "[droplets][9]."

1.  Create a new [DigitalOcean (DO) droplet][9] with [ext4][6] on its main, root filesystem ("rootfs" aka '/')
2.  Lock rootfs with ecryptionion via [fscrypt][2], encrypted with some key file(s), aka "locking/unlocking keys."
3.  [fscrypt presumably presents no special problem for database files, or vice versa.]
4.  _Automatically unlock rootfs at boot time, by reading/applying keys from step (2) or some similar, fully-automated process._
5.  [All files created prior to step (2) are unencrypted.]
6.  [All files created after step (2) are encrypted.]
7.  We use (install software, read/write data, etc) the [droplet][9].
8.  [Days/months/years go by.]
9.  We stop using the droplet and remove all data/services from it.
10. We securely-erase ([secure-delete][10]?) the keys created in step (2).
11. We optionally secure-erase software+data (files and directories) created in steps (7) and (8).
12. We delete the droplet by [DO "destroy"-ing it][11].

**Potential benefit 1**: post-VPS-deletion data security / "proper" deletion<br>
Our team sleeps a little more soundly understanding that DO admins or other DO clients will have a harder time recovering our data created in steps (7) and (8), especially since DO (and other hosting providers) [might keep data around][12] for a while [even after droplet deletion][13]. (Granted, these DO references only mention historical backups retaining data, and these backups could still contain the fscrypt unlocking keys - we do not see a way around this.)

**Potential benefit 2**: "immediate data deletion"<br>
Imagine a slightly different scenario than the one above: our team experiences a crisis, we're really short on time, and we need to immediately "delete" the data and feel confident no on can regenerate it. In this case, we simply [securely-erase][10] _all_ the "unlocking key(s)" (including ones in backups/copies/replications) for the [fscrypt][2]-ed files. If no copies are kept (of the "locking file(s)"), only one secure-delete operation (for one or many files, _in one storage place_) is needed. And poof, no more data available.

**Potential benefit 3**: server-bootup "authority required"<br>
Again, adjusting the above, numbered-bullet-list scenario: let's say that our above server (let's call it _server A_) must first get authorization form a [FreeIPA][14] (or some such auto-policy server; we're new to sysadmin-ing these kinds of systems, too) system in order to decrypt the "[fscrypt][2] unlocking keys" early in _server A_'s bootup stages before it can proceed with the rest of the bootup. And optionally the FreeIPA system might first be required to check-in with a human somehow (maybe via authorization from a trusted mobile device, similar to [Apple's 2FA][15]) before the FreeIPA system can authorize _server A_ to bootup.  

Is all of the above accurate, feasible, and reasonable? If so...

**Big obstacle**. Our largest, current implementation concern: how to perform step (3), unlocking the rootfs at boot time? Are the [fscrypt][2] "unlocking keys" presumably stored on a non-rootfs mount/partition? Is there some other fscrypt or additional, related procedure that can facilitate this? This portion of the system design also plays into benefit 3, above.

**Additional consideration(s)**.

*Some files not protected*. We're not encrypting/protection any files created prior to step (2) (above). Our response: so what? Maybe a malicious attacker gets a log file with some interesting data in it. And while this is not optimal, they won't acquire our primary data assets; and we find this entirely better than no protection at all for any file assets that happen to get stored on the rootfs (instead of an encrypted storage volume).

*DigitalOcean (DO) claims to "scrub" destroyed droplets*. Yes, that's their claim. However, what does AWS and GCP do? We plan to scale to many VPSes in AWS and GCP, possibly more than in DO. Further, our team has no way to validate that DigitalOcean is performing this "scrubbing" activity and to what degree. Additionally, this DO feature does not serve the additional potential benefits mentioned above. Finally: we think it good practice to primarily rely on vendor to implement proper security protocol. If we did, then we'd consider using more "cloudier"/outsourced solutions than what we're currently doing.

**Less-attractive alternatives (to [fscrypt][2]-based design) we see thus far**

*[LUKS][16] on ("under") native rootfs mount*

Possibly preferred, but we can not find a reasonable and reliable way to apply LUKS (or any lower-level, block-storage/disk, [full-disk encryption (FDE)][17]) to VPSes that are already built. However, our initial analysis suggests [it's too cumbersome and/or not automate-able][18] (for constructs we employ like [Terraform][19] and [Ansible][20]) even if we could make it work for a [DigitalOcean droplet][9]--which seems unlikely. (*DigitalOcean engineers*: if it's feasible, please message me.) Thus this option is not scalable for our group environments with a larger number of VPSes. Hence our attraction to relatively flexible, dynamic, post-VPN-build fscrypt "application" (per above) is far more attractive.

*[LUKS][16] on non-rootfs or network-storage mount*

Yes, DigitalOcean (and possibly AWS and GCP) has network-storage-mountable, [LUKS-based "Volumes."][21] However, ensuring all our various software-server apps always "point" to this Volume is a cumbersome and pragmatically-impossible task. We'll probably still employ [DO Volumes][22], but we'd prefer that ALL of our installed files/data/software is protected after step (12), above. Otherwise we have to perform encumbering, continual audits to ensure every single little install update did not add anything to the (unencrypted) rootfs. This is arguably unmaintainable from an operationally-efficient perspective.

And it's fundamentally the same problem, best we can tell, if we try to install a separate, new filesystem on a local/native mount on/in the VPS disk/storage.

*[eCryptfs][23] no longer practical*

It's [apparent author Michael Halcrow][24] [writes][25]: _"Because of performance and functionality issues (file name length, possibility of page cache inconsistency) [eCryptfs shouldn't be used for anything any more."][25]_

*Building our own hardware servers, possibly at our own facility*

This of course takes our operations to a whole new level, a place we'd like to avoid until much further down the road.

  [1]: https://en.wikipedia.org/wiki/Virtual_private_server
  [2]: https://github.com/google/fscrypt
  [3]: https://www.digitalocean.com
  [4]: https://aws.amazon.com/
  [5]: https://cloud.google.com/
  [6]: https://en.wikipedia.org/wiki/Ext4
  [7]: https://github.com/google/fscrypt/blob/master/README.md
  [8]: https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions
  [9]: https://www.digitalocean.com/products/droplets/
  [10]: https://packages.debian.org/sid/utils/secure-delete
  [11]: https://www.digitalocean.com/docs/droplets/how-to/destroy/
  [12]: https://www.digitalocean.com/community/questions/recovering-deleted-purged-droplet
  [13]: https://www.digitalocean.com/community/questions/how-to-recovery-droplets-after-72-unpaid-billing
  [14]: https://www.freeipa.org
  [15]: https://support.apple.com/en-us/HT204915
  [16]: https://en.wikipedia.org/wiki/Linux_Unified_Key_Setup
  [17]: https://en.wikipedia.org/wiki/Disk_encryption
  [18]: https://www.johannes-bauer.com/linux/luksipc/
  [19]: https://www.terraform.io/
  [20]: https://www.ansible.com/
  [21]: https://www.digitalocean.com/docs/volumes/overview/
  [22]: https://www.digitalocean.com/docs/volumes/
  [23]: http://ecryptfs.org/
  [24]: http://ecryptfs.org/about.html
  [25]: https://news.ycombinator.com/item?id=17736379

**Comment by johnnyutahh** [comment]
fyi. I just posted the same question here:

https://security.stackexchange.com/questions/219079/employ-fscrypt-to-protect-post-vps-build-newly-installed-files-from-data-at-res

**Comment by johnnyutahh** [comment]
Latest idea:

Employing custom-built, with ext4 rootfs encrypted at time of OS install, Linux containers (like [docker](https://en.wikipedia.org/wiki/Docker_(software)) or [others](https://en.wikipedia.org/wiki/List_of_Linux_containers)) to work around the hosting-providers limitations. Some container-based rig-up _might_ have a chance to accomplish this goal and all the associated benefits.

We can (maybe) realize this at the cost of spend more money and effort to build out, effectively, virtual machines (containers) on top of virtual machines (VPSes). Or at this point, we rent or co-locate dedicated hardware instead of VPSes - although that dramatically limits our operational (re-deployment, etc) flexibility.

Thoughts on this idea, and any others, very welcome.

**Comment by ebiggers** [comment]
If you want to encrypt a whole filesystem, then dm-crypt is the right solution, not fscrypt.

Also, either way if you write the encryption key to disk it kind of defeats the point, unless you only care about deleting the data and are *really* sure that the key can actually be securely deleted and nothing (e.g. backups, filesystem, SSD wear leveling) has made copies.

**Comment by johnnyutahh** [comment]
@ebiggers writes:
> If you want to encrypt a whole filesystem, then dm-crypt is the right solution, not fscrypt.

Yes. And it's possible this comment overlooks the main point: _we can not do this_ because of limitations from the hosting provider. Hence our investigation. More details in the original post.

Best regards,
~J

**Comment by ebiggers** [comment]
You said only that you want to encrypt the "rootfs".  fscrypt is not whole-filesystem encryption, so you have to choose specific directories you want to encrypt.  It's not supported to mix unencrypted and encrypted files in the same directory.  A possible exception is if you use overlayfs with an encrypted upperdir, which works on Linux v5.2 and later.

**Comment by johnnyutahh** [comment]
@ebiggers writes:
> It's not supported to mix unencrypted and encrypted files in the same directory.

Thus the essential answer might be: we can't do this.  (Without overlayfs/Linux v5.2/etc as noted above.)

Separately, a workaround: we're looking into an idea to create encrypted-volume containers/dockers (inside the VPS). Maybe using something like: https://github.com/containers/docker-lvm-plugin.

**Comment by ebiggers** [comment]
Closing since there don't seem to be any further questions here specifically about fscrypt.
