### ISSUE TITLE
Required key not available for root user to start postgres cluster

### ISSUE THREAD

**Issue by wallbergrep** [google/fscrypt#188]
I want to encrypt the database directory on our postgres servers. 
They run on ubuntu 18.04 with the current 5.4 kernel. In fscrypt.conf the policy is set to V2.
I encrypted the var/lib/postgresql directory with two protectors. Once as root user and as postgres user.
Problem is the root user can create the cluster but cannot start it.
Error message: `could not create lock file "postmaster.pid": Required key not available.` 

Fscrypt status `unlocked: yes.`
The postgres user, however, can start the cluster without problems. The root user can also do this without encryption. I can't find a solution.

**Comment by Maryse47** [comment]
Did you compile fscrypt from latest git snapshot? v2 policy support isn't part of any official release yet.

**Comment by ebiggers** [comment]
As @Maryse47 pointed out, you currently need to compile `fscrypt` from git for v2 encryption policies to be supported.  If you run `fscrypt status` on the directory, does the output include `policy_version:2`?  If not, it's not using a v2 policy.

**Comment by wallbergrep** [comment]
Thank you so much. It is working now with the latest git built. :)
