### ISSUE TITLE
Issue in combination with flatpak

### ISSUE THREAD

**Issue by akallabeth** [google/fscrypt#202]
I´ve had issues with fscrypt and ubuntu 19.10 (added my comments to https://github.com/flatpak/flatpak/issues/3365 )
Since I don´t know what is at fault here I open this issue here to make you aware of it.

**Comment by Maryse47** [comment]
This may be yet another issue with v1 policy and flatpak helper process may not have linked user keyring.

**Comment by akallabeth** [comment]
can confirm, using a self compiled `fscrypt` with a new (copied) home encrypted with `version 2` does work.

**Comment by Maryse47** [comment]
Yeah, so I think this is only solution for you.

**Comment by akallabeth** [comment]
Thanks.
