### ISSUE TITLE
Build isn't reproducible

### ISSUE THREAD

**Issue by ericonr** [google/fscrypt#206]
Hey there!

Several Linux distros (at least Arch, Debian and SUSE) are striving for reproducible builds, as a way to verify build systems and guarantee the legitimacy of build servers and whatnot. The build time injection done in the Makefile makes building fscrypt an unreproducible process.

The Arch Linux [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/fscrypt) already applies a [patch](https://git.archlinux.org/svntogit/community.git/tree/trunk/reprobuild.patch?h=packages/fscrypt) to the Makefile to make it reproducible, and on Debian it's [flagged as unreproducible](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/fscrypt.html). Fixing this issue upstream is probably the best way of widely making fscrypt a reproducible build.

**Comment by josephlr** [comment]
@ericonr, thanks for the report. For the record, I think it should be an explicit goal of fscrypt's development to have a reproducible build. Toward that end, I've opened #207.

PTAL, and let me know if that is not enough to resolve this issue.

**Comment by ericonr** [comment]
Well, that was fast! Thanks for the quick response! This is quite a useful piece of software.

Stay safe!
