### ISSUE TITLE
[rsync] What is the correct way to do backups of fscrypted files with rsync?

### ISSUE THREAD

**Issue by torvic9** [google/fscrypt#210]
Hello,
I get "Required key not available" error message when trying to rsync encrypted (custom passphrase) files from sender to destination. 
Both sender and destination are locked (files should be transferred in encrypted state), both have the same `.fscrypt` directory, and both have ext4 encryption support enabled.
The output of `fscrypt status` is the same on both, however only the sender side can be unlocked, unlocking destination fails with "file or directory not encrypted" - is this due to the fact that destination uses a different directory hierarchy?
Do I first have to create a new `.fscrypt` on the destination?
Or what is the best way to backup encrypted (i.e. locked) files from one filesystem to another?

EDIT: Just read this in the kernel documentation:
> It is not currently possible to backup and restore encrypted files without the encryption key. This would require special APIs which have not yet been implemented.

So if my understanding is correct, this means that I would first
- have to create a new fscrypt on the destination with `fscrypt setup /path/to/dest`, and create new protectors
- unlock both source and destination
- and only then run rsync
- lock everything again
?

(_fscrypt version 0.2.7.0.g2b160ae, fscrypt-git from AUR_)

**Comment by ebiggers** [comment]
There's no way to back up locked encrypted files.  You have to unlock them first.

> So if my understanding is correct, this means that I would first
> 
> * have to create a new fscrypt on the destination with fscrypt setup /path/to/dest, and create new protectors
> * unlock both source and destination
> * and only then run rsync
> * lock everything again

Yes, that would work.  (Except the command to encrypt a directory is `fscrypt encrypt`, not `fscrypt setup`.)
