### ISSUE TITLE
Provide guidance about securing login passphrase

### ISSUE THREAD

**Issue by ebiggers** [google/fscrypt#220]
The security of any encryption system that's unlocked by the user's login passphrase, including `fscrypt`'s login protectors, is limited by the strength of the password hashing in `/etc/shadow`.  `/etc/shadow` by default uses SHA-512 with 5000 rounds, which is much weaker than `fscrypt`'s Argon2 passphrase hashing.  For `fscrypt`, we should provide appropriate guidance in the documentation and in the interactive output when creating a login protector.  We should recommend that users should either [increase the number of rounds in /etc/shadow](https://wiki.archlinux.org/index.php/SHA_password_hashes#Increasing_security), use a strong login passphrase, or use a custom passphrase protector instead.

Longer term, it would be nice if `/etc/shadow` would use a more modern passphrase hashing function, such as Argon2.  That apparently would require making [the `crypt()` function](http://man7.org/linux/man-pages/man3/crypt.3.html) in glibc support it.

**Comment by gerout7** [comment]
What would be a recommended number of round for /etc/shadow?

**Comment by ebiggers** [comment]
> What would be a recommended number of round for /etc/shadow?

In https://github.com/google/fscrypt/pull/223 I'm recommending 500000 (100x the default), as this makes the hashing time be on the same order of magnitude as `fscrypt`'s default.

However, the main recommendation is to choose a strong passphrase.  That can give orders of magnitude more improvement than the 100x you can get by increasing `rounds`.

**Comment by Maryse47** [comment]
Aren't hashing rounds optimized for power of 2? It would be `524288` then.

**Comment by ebiggers** [comment]
> Aren't hashing rounds optimized for power of 2? It would be 524288 then.

No, there's nothing special about powers of 2.  See the source [here](https://sourceware.org/git/?p=glibc.git;a=blob;f=crypt/sha512-crypt.c;h=a1878c4dd441a27d52feb34982efe607507d23d9;hb=9ea3686266dca3f004ba874745a4087a89682617#l278).

**Comment by gerout7** [comment]
Why is the option called nrounds https://github.com/google/fscrypt/blame/master/README.md#L309
Should't it be "rounds"? I did not find an option called nrounds but the manpage of pam_unix lists rounds as the option in question. Is this a typo?

**Comment by ebiggers** [comment]
> Why is the option called nrounds https://github.com/google/fscrypt/blame/master/README.md#L309
Should't it be "rounds"? I did not find an option called nrounds but the manpage of pam_unix lists rounds as the option in question. Is this a typo?

Yes it's a typo, sorry about that!  I used `rounds` when I tested it, but accidentally wrote `nrounds` in the documentation.  Fixing with https://github.com/google/fscrypt/pull/228.

**Comment by gerout7** [comment]
If I am not mistaken the hashing strength of the argon hash is related to the hardware capabilities of the system it is generated on. Meaning it will be a stronger hash when there is a bigger CPU available so it will always take 1 second to generate the hash.  

Wouldn't t be possible to provide a dynamic recommendation when the login passphrase is selected by measuring the number of rounds it takes with sha512 to reach the same time costs?

**Comment by ebiggers** [comment]
It would be possible, but since `/etc/shadow`'s SHA-512 hash isn't multithreaded, the time to execute it doesn't vary nearly as much as the Argon2 hash.  We'd also have to tell the user to run a command to calibrate the SHA-512 hash (which adds UI complexity), and we're now only talking about small changes in security that are equivalent to adding or removing a fraction of a character to your passphrase.  So I'm not sure it would be worthwhile to implement, vs. simply giving a number that's good for most users.  I'll think about it.

**Comment by ebiggers** [comment]
For now I'm considering this issue to be closed by https://github.com/google/fscrypt/commit/1fbde0288b2d53d4e811b8869979429a57bff58f and https://github.com/google/fscrypt/commit/bc9f5e542745f102de70ade555114eb28591fcd1, as those addressed what I intended to be in-scope for this issue originally.  Providing a command like `fscrypt calculate-shadow-rounds` would be getting somewhat out-of-scope for `fscrypt`. It would probably be better handled by the `shadow` package, which also should be updated to support Argon2.
