### ISSUE TITLE
error: constant overflows int

### ISSUE THREAD

**Issue by Tcll** [google/fscrypt#231]
on Void Linux i386 with release 0.2.7 running `make` with defaults...

these constants:
```
unix.FS_IOC_REMOVE_ENCRYPTION_KEY
unix.FS_IOC_REMOVE_ENCRYPTION_KEY_ALL_USERS
```
raise the errors:
```
keyring/fs_keyring.go:231:6: constant 3225445912 overflows int
keyring/fs_keyring.go:235:7: constant 3225445913 overflows int
```

if I can modify this source or provide make flags to fix the issue, please instruct me how
I'm neither a go programmer, nor do I have much experience compiling stuff ;)

**Comment by ebiggers** [comment]
Already fixed by https://github.com/google/fscrypt/commit/c5764330ebc69f15b9bf13b94cfef45732864b5a.

**Comment by Tcll** [comment]
Thanks, and verified that works ;)

also unlike the fix, I modified line 235 as well with the same thing
