### ISSUE TITLE
Recommended upgrade procedure for V2 encryption policies on fresh install

### ISSUE THREAD

**Issue by Redsandro** [google/fscrypt#236]
I'm not sure how to proceed.

On Ubuntu 18.04 LTS or Mint 19 machines with a pre-5.4 kernel and a separate `/home` partition encrypted using the old `fscrypt` V1 encryption policies, what would be the recommended or simplest way to upgrade `fscrypt` using the same `/home` while formatting the rest and installing Ubuntu 20.04 or Mint 20?

__:warning: One thing to take into account is that - unlike `ecryptfs` - we can't decrypt the `/home` using `pam_passphrase` even if we use the same login passphrase for our new Linux installation.__

### Initial thoughts

Still on old system.

1. Shrink the size of your home e.g. remove downloads, media, use `bleachbit`
1. logout from users in `/home`. login as `root`.
1. add a `custom_passphrase` to `/home/redsandro`
    ```bash
    fscrypt metadata create protector /home/redsandro
    fscrypt status /home/redsandro
    fscrypt metadata add-protector-to-policy --protector=/home/redsandro:[protector id] --policy=/home/redsandro:[policy id]
    ```
1. `mv /home/redsandro{,-old}` - we want to re-use this name on the new installation
1. Install Ubuntu 20.04, formatting everything except `/home`
1. Use `redsandro` as default user, do _not_ use encryption
1. On new Linux 5.4 system, log in as `root`, setup `fscrypt`:
    ```bash
    apt install fscrypt libpam-fscrypt
    sed -i 's/"filenames": "AES_256_CTS"/"filenames": "AES_256_CTS",\n\t\t"policy_version": "2"/g' /etc/fscrypt.conf
    fscrypt setup
    fscrypt setup /
    fscrypt setup /home
    rm -rf /home/redsandro/* # Empty new home
    fscrypt encrypt /home/redsandro # pam_passphrase
    fscrypt unlock /home/redsandro-old # custom_passphrase
    rsync -va --info=progress2 --info=name0 /home/redsandro{-old,}/
    rm -rf /home/redsandro-old
    fscrypt metadata create protector /home/redsandro # Add custom_passphrase for rescue purposes
    ```

Am I making this too complicated? Any hints before I back myself into a corner?

**Comment by Redsandro** [comment]
I'm sorry, I forgot to close this issue. Thanks for the help.

Wish Ubuntu would update their fscrypt package to 0.2.9 in Ubuntu 20.04, because their version is so outdated, everyone would have to compile themselves.

Any place where we can add weight to lobby?

**Comment by azazar** [comment]
> Any place where we can add weight to lobby?

As far as I know, only [here](https://bugs.launchpad.net/ubuntu/+source/fscrypt/+bug/1882993). There is a barely noticeable link that shows how many users are affected.
