### ISSUE TITLE
home partially unlocked after logout

### ISSUE THREAD

**Issue by Redsandro** [google/fscrypt#241]
I've taken a closer lock to some systems upgraded to `policy_version:2` with `fscrypt` 0.2.9 on Ubuntu 20.04\*.

### Observed

Before logging the user with the encrypted home in, doing a `fscrypt status /home/user` (as root) shows the following, which is expected:

> Unlocked: No

After logging the user in, and logging out again, the encrypted home doesn't seem to be (completely) locked again:

> Unlocked: Partially (incompletely locked, or unlocked by another user)

It is also possible to see all the file names, which would appear garbled in a locked state. I can _not_ see the contents of the files. I did not have this on `policy_version:1`.

### Expected

After logging a user out, the _Unlocked_ state of the home directory should again be _No_.

---

\*) Secretly I'm using Linux Mint 20, which is based on Ubuntu 20.04 LTS.

**Comment by ebiggers** [comment]
> Unlocked: Partially (incompletely locked, or unlocked by another user)

You can only get this message if the directory is using a v1 encryption policy.  So if you think you're using v2, something is wrong.  Remember that existing directories stay as v1 even if you edit `/etc/fscrypt.conf`; upgrading a directory requires re-creating it.

Also, note that auto-locking isn't completely reliable currently due to a systemd bug (https://github.com/systemd/systemd/issues/8598), which we might have to work around by replacing pam_fscrypt with a systemd service (https://github.com/google/fscrypt/issues/95).

**Comment by Redsandro** [comment]
I will check and get back to this. Perhaps I was too hasty and forgot to swap `user-new` with `user` after rsyncing.

**Comment by Redsandro** [comment]
@ebiggers I verified and I did the directory swap. After logging out and logging in with root on a tty, I get this:

> Options:  padding:32 contents:AES_256_XTS filenames:AES_256_CTS policy_version:2 
> Unlocked: Partially (incompletely locked, or unlocked by another user)

After compiling and installing the newer `fscrypt` tools, I rebooted, logged in, created a `user-new` in `home`, fscryped it with policy version 2, rsynced `user` into `user-new`, logged out, moved `user` to `user-old` and `user-new` to `user`, rebooted and logged in.

Everything works fine, except the described issue.

**Comment by ebiggers** [comment]
Are you 100% sure that it says both `policy_version:2` and `Partially (incompletely locked, or unlocked by another user)`?  With v2, the status can show `Partially (incompletely locked)`.  But it should never show the `unlocked by another user` part; that's specific to v1.

Anyway, as I mentioned, auto-locking is known to be unreliable currently (https://github.com/google/fscrypt/issues/66, https://github.com/google/fscrypt/issues/95).  I.e. it is "expected" to see `Partially (incompletely locked)` sometimes.

**Comment by Redsandro** [comment]
@ebiggers I am not 100% sure; I saw some things like the brackets and the v2, and my brain imagined the rest. I will have to check again. :sweat_smile: 

Hard to copy paste from tty. Will start a typescript next time.

**Comment by Redsandro** [comment]
You were correct @ebiggers. It says `Partially (incompletely locked)`. I understand this is expected with v2 policy.

What exactly does this mean? What is not locked for whom? Only the filenames? Only for root?

I'll follow the upstream issue and the #95 one. This can be closed.

**Comment by ebiggers** [comment]
> You were correct @ebiggers. It says Partially (incompletely locked) now. Apologies for rushing. I did not read the exact difference between steps, it just seemed similar at a glance. Lesson learned. Either way, I understand this is expected with v2 policy.
>
> What exactly does this mean? What is not locked for whom? Only the filenames? Only for root?

It means that the encryption policy key (the master key that unlocks the whole directory) has been removed, but some files were still open at the time of the key removal, so their per-file keys are still loaded.  These files can still be opened.  The filenames of any parent directories of such files will still be visible too.

For example if the directory `/a` is encrypted, and you run `fscrypt lock /a` while the file `/a/b/c` is open, then the per-file keys for `/a`, `/a/b`, and `/a/b/c` will remain.  But other files or subdirectories of `/a` that weren't open, like `/a/d`, will be locked.
