### ISSUE TITLE
`err` may be `nil` and cause a crash

### ISSUE THREAD

**Issue by nabice** [google/fscrypt#242]
https://github.com/google/fscrypt/blob/097234779e2ac5e904804802e14ec74e2028d168/cmd/fscrypt/commands.go#L996
https://github.com/google/fscrypt/blob/097234779e2ac5e904804802e14ec74e2028d168/cmd/fscrypt/errors.go#L292

**Comment by ebiggers** [comment]
We should fix this for robustness, but I don't see how `err` can be `nil` here.  It should be impossible.  Do you have a reproducer?

**Comment by nabice** [comment]
@ebiggers 
I use a code scanning tool and it tells me that `AddProtector` may return nil, as shown below:
https://github.com/google/fscrypt/blob/097234779e2ac5e904804802e14ec74e2028d168/actions/policy.go#L460
If it cannot be nil, please close this issue.
Sincerely.
