### ISSUE TITLE
Document interaction with systemd-homed --storage=fscrypt

### ISSUE THREAD

**Issue by josephlr** [google/fscrypt#246]
[systemd-homed](https://wiki.archlinux.org/index.php/Systemd-homed) allows for [fscrypt-encrypted home directories](https://wiki.archlinux.org/index.php/Systemd-homed#fscrypt_directory).

However, this does not use the fscrypt userspace tool, just the kernel functionality. We should document the tradeoffs of using `homectl` vs this tool. We should also make it clear that this userspace tool doesn't do anything to fscrypt encrypted home directories. We could (in theory) also add checks in the command-line tool to properly handle cases where a user tries to operate on the systemd-managed home directories.

**Comment by ebiggers** [comment]
The difference between `fscrypt` and `systemd-homed` is explained in the README now, so I am considering this to be resolved.
