### ISSUE TITLE
Login-passphrase not working with kernel-mounted rootfs

### ISSUE THREAD

**Issue by fgndev** [google/fscrypt#254]
My encrypted home directory works fine as long as the root filesystem is mounted by initrd. After removing the initrd from my bootconfig, my home directory was no longer unlocked on login.
So with the root filesystem mounted via the kernel cmdline using root=PARTUUID=XXXX-XXXX fscrypt does not find the root device (the uuid the protector links to is correct).
Since the protector for my home directory has the correct UUID and it works when I boot using an initial ramdisk I am assuming that fscrypt, after looking up the device node by the UUID in the protector link, looks in /proc/self/mounts|mountinfo which on my system do not list the actual device node but /dev/root.

**Comment by ebiggers** [comment]
This sounds like the bug that was fixed by https://github.com/google/fscrypt/pull/154/commits/c7da2443d6ffa51727db09f8ef1df6aea8c7612c.  Which version of `fscrypt` are you using?  If it's not the latest version, please upgrade.

**Comment by ebiggers** [comment]
@fgndev, any update?

**Comment by ebiggers** [comment]
No feedback from reporter, so I'm assuming this was solved by the commit I mentioned above.  Please re-open if this is still an issue.
