### ISSUE TITLE
"decrypting" a directory permanently

### ISSUE THREAD

**Issue by daeyun** [google/fscrypt#255]
Hi,

I have an encrypted home directory. I'd like to undo everything I did with fscrypt and turn it into a plain unencrypted directory.
What is the recommended way to do this?

**Comment by ebiggers** [comment]
Just make a copy of the directory, and replace the original with it.  E.g.:

    cp -a -T dir dir.unencrypted
    rm -rf dir
    mv dir.unencrypted dir
