### ISSUE TITLE
use_fs_keyring_for_v1_policies setting does not work as expected (Ubuntu 20.04)

### ISSUE THREAD

**Issue by fixmaker** [google/fscrypt#259]
On my Ubuntu 20.04 installation I used fscrypt (0.2.5 - from the Ubuntu repo) to set up my encrypted home directory, unlocked by PAM on login. This works fine.

Then I discovered there were problems with cron scripts that accessed the contents of my home directory (even _after_ I have logged in and the directory was unencrypted). I was getting "Required key not available" errors.

I think this was a manifestation of the filesystem keyring issue described [here](https://github.com/google/fscrypt#cant-log-in-with-ssh-even-when-users-encrypted-home-directory-is-unlocked). So I followed those directions and added `"use_fs_keyring_for_v1_policies": true` to my `/etc/fscrypt.conf`.

Unfortunately, this doesn't work. I added another user account to my machine. After logging in under my own account (thus decrypting my home directory) if I concurrently log in as a different user I can list the contents of my home directory but any attempts as a different user to view the _contents_ of any files results in a "Required key not available" error.

Maybe I misunderstood the documentation, but I thought that after enabling `use_fs_keyring_for_v1_policies` then any user on my machine should be able to access the contents of my decrypted home directory.

**Comment by ebiggers** [comment]
That option requires `fscrypt` 0.2.6 or later.  Please try upgrading to the latest version of `fscrypt`.
