### ISSUE TITLE
Bash completion for the fscrypt command

### ISSUE THREAD

**Issue by audeoudh** [google/fscrypt#260]
fscrypt lacks of a bash completion script.

I have written such a completion script, compatible with [scop/bash-completion](https://github.com/scop/bash-completion) toolkit.  According to their contributing guidelines, “before submitting a completion to us, first consider submitting it to the project that ships the commands your completion is for”.

Is the google/fscrypt's team interested in such a script?

**Comment by josephlr** [comment]
Yes we would be interested, I'm wondering if it's possible to generate the autocompletions directly from the source code.

**Comment by audeoudh** [comment]
Generate completions (i.e. run the program and get completions from it) or generate completion script, used during completion?

I do not know automated tools for generating completion scripts.  Some parts are really specialized, such as code that extracts the possible mountpoints or protector / policy IDs; some are general, and may be more easily extracted from it, such as the list of commands.

**Comment by ebiggers** [comment]
Done by https://github.com/google/fscrypt/pull/261.  Thanks!
