### ISSUE TITLE
Any user can see the files once the folder is unlocked by root

### ISSUE THREAD

**Issue by flixman** [google/fscrypt#262]
I have an installation of Debian 10.6, using fscrypt 0.2.4-2+b10.
I log in as a temporary user, then su -l to become root, and I setup fscrypt the following:

    apt install -y fscrypt libpam-fscrypt keyutils
    pam-auth-update --package fscrypt
    tune2fs -O encrypt /dev/sda1
    fscrypt setup --force
    fscrypt setup /

At this moment, I create a folder and encrypt it and put a file on it
    mkdir /kk
    echo 'test' | fscrypt encrypt /kk --user=root --source=pam_passphrase
    echo 'hi' > /kk/tmp.txt

If I log in as another user, I can see the unencrypted contents of /kk, as well as the contents of /kk/tmp.txt. If I log out from my root session, then I do not see any of them. Is this a bug, or am I doing something wrong?
EDIT: If I log in as root again, with both my non privileged user and my root user I can see the contents of the encrypted folder and file.

**Comment by Maryse47** [comment]
If access to folder isn't restricted by unix permissions, mac or whatever then when any user unlocks folder all other users will be able to access it as well. This works as expected. You should use access control on top of encryption. See also https://github.com/google/fscrypt/issues/61

**Comment by ebiggers** [comment]
Yes, this is working as intended.  Also see https://www.kernel.org/doc/html/latest/filesystems/fscrypt.html#unauthorized-file-access.
