### ISSUE TITLE
Unlocked access for a group?

### ISSUE THREAD

**Issue by MrM40** [google/fscrypt#266]
I would like to encrypt a folder in my Samba share and allow access for a group, not just a single user.
Using ACL whould also be OK.

Is this possible?

I did try to use a group in the option `--user=GrpName` but it didn't work.

**Comment by ebiggers** [comment]
While an encrypted directory is unlocked, it is unlocked for everyone.  Encryption isn't access control.

Just use `chgrp` and `chmod` on the directory to restrict access to the group.

(Note, I'm assuming you're using `fscrypt` v0.2.7 or later and Linux kernel v5.4 or later, so that the default is v2 encryption policies rather than v1.  v1 encryption policies worked a bit differently.  If you're using an older version of `fscrypt` or the kernel, please upgrade.)

**Comment by MrM40** [comment]
"unfortunately" I'm running Debian stable (Buster), but I can upgrade the kernel from test and give it a try, updating fscrypt too of course. 

Thank's for the feedback.

**Comment by ebiggers** [comment]
> I would like to encrypt a folder in my Samba share 

Also please be aware that `fscrypt` only supports the ext4, f2fs, and ubifs filesystems, and only when accessed directly.  If you're talking about encrypting or unlocking a directory via cifs, or enabling the native file encryption on an NTFS filesystem (which is totally different) via cifs, that's not possible with `fscrypt`.

**Comment by ebiggers** [comment]
You can encrypt and unlock a directory on ext4/f2fs/ubifs, which is then shared via a Samba server.  But clients won't be able to unlock or lock the directory themselves; that can only be done on the server.

**Comment by MrM40** [comment]
Yes, ext4 and running all fscrypt related on the server. The client just connect to the Samba server

**Comment by myomv100** [comment]
> You can encrypt and unlock a directory on ext4/f2fs/ubifs, which is then shared via a Samba server. But clients won't be able to unlock or lock the directory themselves; that can only be done on the server.

You can only read files of fscrypt encrypted, unlocked  and smb shared directories.  

Writing files isn't possible from the an smb shared folder even if this folder was properly encrypted and unlocked with fscrypt.

**Comment by ebiggers** [comment]
> You can only read files of fscrypt encrypted, unlocked and smb shared directories.
> 
> Writing files isn't possible from an smb shared folder even if this folder was properly encrypted and unlocked with fscrypt.

Writing should work too.

Did you make sure you're [using v2 encryption policies](https://github.com/google/fscrypt#cant-log-in-with-ssh-even-when-users-encrypted-home-directory-is-unlocked)?

**Comment by myomv100** [comment]
> > You can only read files of fscrypt encrypted, unlocked and smb shared directories.
> > Writing files isn't possible from an smb shared folder even if this folder was properly encrypted and unlocked with fscrypt.
> 
> Writing should work too.
> 
> Did you make sure you're [using v2 encryption policies](https://github.com/google/fscrypt#cant-log-in-with-ssh-even-when-users-encrypted-home-directory-is-unlocked)?

Just upgraded to kernel 5.9 and  v2 policies supported and it fixed the issue with smb / ssh data write  !

Many thanks!
