### ISSUE TITLE
Destroying an in-use protector should be forbidden?

### ISSUE THREAD

**Issue by johnsutton** [google/fscrypt#272]
With v0.2.9 you can successfully "metadata destroy --protector X" even though the protector is currently in use with a policy, and it then becomes impossible to remove-protector-from-policy because "protector metadata for X not found on filesystem Y".

Arguably, either the destroy should be forbidden OR all uses of the protector should be removed at the same point.

And a small bugette: if you attempt to unlock a directory which is using a policy which is "protected" by such a non-existent protector (in addition to one or more real, existing protectors) then you get a printf output with uninstantiated %placeholders:

The available protectors are: 
1 - login protector for someuser
2 - custom protector "newprot"
NOTE: %d of the %d protectors failed to load. You may need to mount a linked filesystem. Run
with --verbose for more information.Enter the number of protector to use:

Other than this... great work!  Thanks :)

**Comment by mahiarmody** [comment]
I completely agree. I'd like to offer additional possibilities too. In addition to to the above-mentioned options suggested:
1. Forbid the deletion of a protector in use, stating that it must first be removed from all policies using it.
OR
2. The protector should be automatically removed from all policies using it and this should be stated as a warning.

Also alternatively,
3. Provide a new subcommand that cleans off all such junk / dangling protector entries from all policies.
OR
4. Modify the existing `fscrypt metadata remove-protector-from-policy` command to ignore the error:
`scrypt metadata remove-protector-from-policy: protector metadata for <protector ID> not found on filesystem <mountpoint>` 
and proceed with removal of the deleted protector from the policy. After all a deleted protector can't be used any way, so why keep it?

**Comment by josephlr** [comment]
@johnsutton @mahiarmody thanks for bringing this up. I agree that this workflow needs to be improved. I was able to get into a similar situation by manually deleting protector files in the `.fscrypt` metadata directory.

At the very least, we should allow `fscrypt metadata remove-protector-from-policy` to work even if the protector doesn't exist. The current functionality puts users in an unfixable state.

**Comment by ebiggers** [comment]
https://github.com/google/fscrypt/pull/338 will make it possible to use `fscrypt remove-protector-from-policy` even if the protector no longer exists. 

I'm not sure that the command to destroy a protector needs to be changed too.  Regarding forbidding destroying an in-use protector: people might want to do this intentionally.  Regarding automatically finding and updating all policies: that would require a global scan, which would be preferable to avoid.  For now I'd just like to fix `fscrypt metadata remove-protector-from-policy`.
