### ISSUE TITLE
pam_fscrypt quietly fails if passwd is set by root user

### ISSUE THREAD

**Issue by kostja** [google/fscrypt#273]
I just started using fscrypt on Ubuntu 20 to encrypt my home directory using login protector. Then I tried to change my password with passwd, and noticed that the home folder was not recrypted. Tracing the log files discovered this:
pam_fscrypt[1986]: Chauthtok(map[]) failed: could not get OLDAUTHTOK: item not found

The trouble is that I don't know what to do now. I can't revert to the old password since it was set at install time and is too weak.

**Comment by johnsutton** [comment]
You could try to bring things back into sync using:

fscrypt metadata change-passphrase --help

but fixing the underlying problem of the automatic syncing failing is obviously a good idea!  I've also just started using fscrypt for my home directory but haven yet attempted to change my password.  I will give it a go before I travel any further down this path!

**Comment by ebiggers** [comment]
Running `passwd USER` as root assigns a user a new password without having to enter their existing one.

It's impossible for the user's `fscrypt` protector (if they have one) to get re-wrapped in that situation because the user's existing passphrase is needed to unlock it first.
                                                                                
So I'm not sure that anything can be done about this.

It probably would be possible to deny the root user the ability to change passwords.  But that would be unexpected too.

**Comment by kostja** [comment]
All I'm asking is that this makes  it into the manual. Steps for recovering for people who made this mistake would also be useful. fscrypt metadata documentation is rather bare, e.g. where do I take ID from?

**Comment by ebiggers** [comment]
It's [already covered in the troubleshooting section](https://github.com/google/fscrypt#i-changed-my-login-passphrase-now-all-my-directories-are-inaccessible).

**Comment by josephlr** [comment]
@ebiggers can we close this? The only thing I can think of is having pam_fscrypt output some sort of "warning" if something like this happens. Do you know if there is a way to do this?

**Comment by ebiggers** [comment]
There might be a way to do that; that's why I haven't closed this issue yet.

**Comment by josephlr** [comment]
We might be able to use `pam_message` (see https://linux.die.net/man/3/pam_conv) to display a message to the user that a certain action has failed (without blocking the entire password reset process). This is what some other PAM modules do.

**Comment by ebiggers** [comment]
https://github.com/google/fscrypt/pull/334 will cause a warning message to start being printed, e.g.:

```
# passwd testuser
New password: 
Retype new password: 

pam_fscrypt: cannot update login protector for 'testuser' because old passphrase
was not given.  This is expected when changing a user's passphrase as root.
You'll need to manually update the protector's passphrase using:

   fscrypt metadata change-passphrase --protector=/:74b53c0ce5897ebc

```
