### ISSUE TITLE
Fscrypt ontop fo luks full disk encryption 

### ISSUE THREAD

**Issue by kocjs** [google/fscrypt#279]
### QUESTION:
I it possible to setup fscrypt on top fo luks full disk encryption? I have to share my machine with other people, we use the same user, to avoid login and out constantly. I want to password protect just some directories so the other user want.

There is no output when i try to check the block size.
`sudo tune2fs -l /dev/mapper/a485----vg-root | grep 'block size'`
It does not feel safe to proceed with
`sudo tune2fs -O encrypt "/dev/dm-2"`

All tutorials i have found set up an encrypted home directory, there is no documentation on how to accomplish this.

Please give me advice.

**Comment by ebiggers** [comment]
Yes, this is possible, as [mentioned in the README](https://github.com/google/fscrypt#other-encryption-solutions).  Just set up LUKS normally, then after that, set up `fscrypt` normally.

**Comment by ebiggers** [comment]
> There is no output when i try to check the block size.
> sudo tune2fs -l /dev/mapper/a485----vg-root | grep 'block size'

Please note that it's `Block size`, not `block size`.

**Comment by kocjs** [comment]
Thanks @ ebiggers

Indeed the `Block size` makes the difference.

Is it safe to proceed with a setup system or do I need a fresh install?

Best kocj

**Comment by ebiggers** [comment]
> Is it safe to proceed with a setup system or do I need a fresh install?

You can start using `fscrypt` at any time; however, encryption can only be enabled on empty directories.

**Comment by kocjs** [comment]
Thank you this worked well.
