### ISSUE TITLE
is fscrypt user tool FIPS compliant?

### ISSUE THREAD

**Issue by jerry-cherry** [google/fscrypt#294]
Hi,

I am considering to use `fscrypt` to encrypt directory files and just wondered if fscrypt user tool is complaint with FIPS. If so, would it be possible to get the CMVP number for that? If not, is there any plan to get the certification?

Thanks,
jerry

**Comment by ebiggers** [comment]
No, there is no plan to get a FIPS certification.

**Comment by jerry-cherry** [comment]
Thanks for the quick response.
