### ISSUE TITLE
Whether custom_passphrase can be figured out from /mnt/disk/.fscrypt?

### ISSUE THREAD

**Issue by animebing** [google/fscrypt#298]
After `setup` and `encrypt` `/mnt/disk` using `custom_passphrase`, there is a directory `/mnt/disk/.fscrypt` which has  `policies` and `protectors`, so I want to know whether others can figure out `custom_passphrase` from these two directories or somewhere else?

**Comment by josephlr** [comment]
Nope! That would be a huge problem (as it would allow any disk encryption to be bypassed.

The data stored in those directories is just fscrypt's cryptographic metadata. These files allow the `fscrypt` tool to know:
  - Which policies use which protectors
  - Policy and Protector IDs
  - The type of the protector (login, custom, etc...)
  - The encryption options in use (algorithm, version, etc...)
  - The _name_ of the custom protector (so you can give them reasonable names like "Backup Password")

The actual protector (like a `custom_passphrase`) is never persisted anywhere. It is only used to unwrap the corresponding policy. This policy is then directly passed to the kernel. All secrets are then wiped from fscrypt's memory (and never written/paged to disk).

**Comment by josephlr** [comment]
If you want to see exactly what's in those files:

files in `protectors` will have this data:

https://github.com/google/fscrypt/blob/a331242c9cf3908fd0c87536a4f13873ab984ecd/metadata/metadata.proto#L48-L60

files under `policies` will have this data:

https://github.com/google/fscrypt/blob/a331242c9cf3908fd0c87536a4f13873ab984ecd/metadata/metadata.proto#L89-L94

The full design document can be found under https://github.com/google/fscrypt#features

**Comment by animebing** [comment]
@josephlr I got it, thanks for your quick and detailed response.
