### ISSUE TITLE
Can I decrypt directory in another computer if I know custom_passphrase?

### ISSUE THREAD

**Issue by animebing** [google/fscrypt#301]
If I know the `custom_passphrase`, whether it is possible to **decrypt the directory in another computer**. If it is the case, how can I do it, thanks.

**Comment by ebiggers** [comment]
Yes, you can use `fscrypt unlock` on another computer to unlock a directory that is protected by a `custom_passphrase` protector.  This works because for `custom_passphrase`, all the `fscrypt` metadata is stored on the same filesystem as the directory itself.

**Comment by animebing** [comment]
@ebiggers  Do I need to copy `/.fscrypt` directory and `/etc/fscrypt.conf` to another computer?

**Comment by animebing** [comment]
When I am trying to `scp` encrypted directory from one machine to another one, there is error `cannot open xxx/aaa' for reading: Required key not available`

**Comment by animebing** [comment]
@ebiggers Here I will clarify why I need to decrypt the directory on another machine

1. I am going to deploy my software on my clients' computers and I plan to pack my software in a virtual machine, so I encrypt  my software directory using `fscrypt`. In order to prevent my clients from accessing my software, I decrypt the directory during booting without login.
2. I find the virtual machine disk file can be unpacked, which means my clients have the chance to know my `custom_passphrase`, but I found the encrypted file after unpacking is different from that in the virtual matchine. so I want to know whether my clients can get decrypted file from the unpacking file using `custom_passphrase`?

**Comment by ebiggers** [comment]
> @ebiggers Do I need to copy /.fscrypt directory and /etc/fscrypt.conf to another computer?

Just the encrypted directory and the `.fscrypt` directory at the root of the same filesystem is sufficient.

> When I am trying to scp encrypted directory from one machine to another one, there is error cannot open xxx/aaa' for reading: Required key not available

Encrypted files can't be copied while they are locked.  They would have to be present on the VM's disk image in the first place.

> I am going to deploy my software on my clients' computers and I plan to pack my software in a virtual machine, so I encrypt my software directory using fscrypt. In order to prevent my clients from accessing my software, I decrypt the directory during booting without login.

What you're trying to do is impossible.  At some point the encryption key or password has to be provided to your client in order for the software to actually run, and at that point they will have access to your software.
