### ISSUE TITLE
Doesn't work in multiple mount point scenarios

### ISSUE THREAD

**Issue by shaojijie** [google/fscrypt#316]
I have multiple hard drives, mounted under different mount points. When I perform the "fscrypt setup" operation on only one of them, and then perform "fscrypt encrypt" in other mount point directories, it fails, and the error message is "fscrypt encrypt: filesystem ***** not setup for use with fscrypt ". Does this mean that I have to perform the "fscrypt setup" operation on the mount point of each hard disk?

**Comment by ebiggers** [comment]
Yes, `fscrypt setup` needs to be run on each filesystem on which you want to use `fscrypt`.
