### ISSUE TITLE
In fscrypt user space, after removing the key from key ring, the encrypted directories file names continues to be in clear form.

### ISSUE THREAD

**Issue by pandiaraj88** [google/fscrypt#369]
I am using fscrypt kernel space and fscryptctl at user space to make use of the fscrypt encryption tool.
I have encrypted a directory using add_key -> set_policy->created valid data files under the encryption directory.
Before I remove the key, I have confirmed the open files of the directory is closed properly.
Now, if I remove the key from the key ring, the file names of the encrypted directory continues to be in clear form. The file names are change to encrypted form only if I reboot the system or if I dorp the cache/inode using the system echo 2 >/proc/sys/vm/drop_caches.

Is there a way to handle this neatly and make the file names as encrypted name upon removing the key from kernel key ring? I do not wish to drop the entire system caches
I have tried this on both Ubuntu machine and my customised embedded system as well. The observation is same.

**Comment by ebiggers** [comment]
This is the wrong place for `fscryptctl` issues, but anyway this is expected if you are using the old version of `fscryptctl` (v0.1.0).  Please use the latest version of `fscryptctl` (v1.0.0) which has the `fscryptctl remove_key` command.

If this doesn't help then please file an issue at https://github.com/google/fscryptctl/issues.

**Comment by pandiaraj88** [comment]
Thanks a lot. I was using latest fscryptctl version. Now posted the query on fscryptctl forum.
