### ISSUE TITLE
Is it good Idea to copy and reuse policy on other device? Is it good idea to copy and reuse a protector?

### ISSUE THREAD

**Issue by ardabro** [google/fscrypt#397]
Typical scenario: home on ssd and additional huge hdd storage for big stuff - both unlocked at login.
the login protector is common, right?
but I'd consider just copying the policy and recovery protector to the second drive to reuse them - just for simplicity.
Will it work? Is it a good idea?

**Comment by ebiggers** [comment]
I *think* that would work and still be secure, but it's not a recommended flow, and the automated tests for `fscrypt` do not test that scenario.  I recommend just using `fscrypt encrypt` to set up each encrypted directory.

**Comment by ardabro** [comment]
Thanks, I took the risk ;)
