### ISSUE TITLE
looking for commit 7c80c73c084ce9ea49a03b814dac7a82fd7b4c23 

### ISSUE THREAD

**Issue by kjlau0112** [google/fscrypt#414]
Hi folks we are building yocto scarthgap  and it current taking source revision of 7c80c73c084ce9ea49a03b814dac7a82fd7b4c23  as shown  https://git.yoctoproject.org/meta-security/tree/recipes-security/fscrypt/fscrypt_1.1.0.bb?h=scarthgap
and it not buildable due to 7c80c73c084ce9ea49a03b814dac7a82fd7b4c23  is not available on this github, are this revision get overwrite or something? what is equivalent revision of this should i refer to?

**Comment by josephlr** [comment]
I do not recognize that particular commit hash or that website, and fscrypt has not released a version `1.1.0`. I would recommend only building from our tagged releases, see https://github.com/google/fscrypt/tags

**Comment by kjlau0112** [comment]
than should developer Armin Kuster to look into this further, thx for response
