### ISSUE TITLE
Release tarballs don't retain version information

### ISSUE THREAD

**Issue by tyhicks** [google/fscrypt#46]
The Makefile contains logic to build a version string by using `git describe --tags` and inject it into the fscrypt build. This allows `fscrypt --version` to print a version string. However, the version information can't be gathered when building from the release tarballs since there's no git tree available and `fscrypt --version` doesn't include any version information in the output.

**Comment by josephlr** [comment]
You're absolutely right on this. I'll just put an actual version in the makefile, and have it overridden if the version info can't be gathered form `git describe --tags`.
