### ISSUE TITLE
[documentation] ext4 encryption and grub

### ISSUE THREAD

**Issue by ghost** [google/fscrypt#58]
https://github.com/google/fscrypt#getting-encryption-not-enabled-on-an-ext4-filesystem

> Note: It is actually possible to get GRUB to boot an encrypted ext4 filesystem. However, it requires GRUB 2.02 (NOT the 2.02 beta) to be installed as the bootloader. As this version was released in April 2017, most systems WILL FAIL TO BOOT with an ext4 encrypted boot directory

This information is not 100% accurate. grub 2.02 was tagged 2017-04-25: https://git.savannah.gnu.org/cgit/grub.git/commit/?id=e54c99aaff5e5f6f5d3b06028506c57e66d8ef77

Ext4 encryption patch landed 2017-06-29: https://git.savannah.gnu.org/cgit/grub.git/commit/?id=734668238fcc0ef691a080839e04f33854fa133a so it's not part of 2.02 upstream release.

Debian cherry-picked this patch to their 2.02 package https://anonscm.debian.org/cgit/pkg-grub/grub.git/commit/?id=29c8a3e93ad5c37599ac3281e59a7452c7c23928 but not every distro did.

Just found this hard way with grub rescue shell :smile:

**Comment by josephlr** [comment]
Ya that's entirely on me. My teammate submitted that patch. I should have remembered the date he submitted it. 😬

I'll update the docs and include a _test_ to check if your version has cherry picked the patch.
