### ISSUE TITLE
Set a more reasonable ramLimit

### ISSUE THREAD

**Issue by josephlr** [google/fscrypt#73]
Fscrypt generates a reasonable set of defaults password hashing costs when creating `/etc/fscrypt.conf`. However, the [`ramLimit` function](https://github.com/google/fscrypt/blob/8e234ec2cbbb4214ca493ddff18257f0c7605ee1/actions/config.go#L206-L207) is simply half the available system ram.

This poses a problem when using fscrypt on removable media. A password protector setup on a computer with a large amount of memory would be difficult to use on a computer with a small amount of memory. There is no real reason to consume multiple GiBs of RAM, the used memory just needs to not fit in any CPU caches.

[Cryptsetup V2](https://www.kernel.org/pub/linux/utils/cryptsetup/v2.0/v2.0.0-ReleaseNotes) uses a memory cost of 128MiB, which would be OK for any reasonable Linux system (Debian has a [minimum memory of 128MiB](https://www.debian.org/releases/stable/amd64/ch03s04.html.en) on `amd64`).

This change would be completely backwards compatible, only changing the generated values for new `/etc/fscrypt.conf` files.

**Comment by fancytenseletters** [comment]
> Cryptsetup V2 uses a memory cost of 128MiB, which would be OK for any reasonable Linux system (Debian has a minimum memory of 128MiB on amd64).

Cryptsetup release note wasn't updated for last minute change before actual release.
https://gitlab.com/cryptsetup/cryptsetup/commit/3c2f92a7afc2ae4c99fa937f1b189bc1375374ad see http://www.saout.de/pipermail/dm-crypt/2017-December/005773.html
> Default for Argon2i is now 1GB of memory and 2 seconds iteration time (can be changed during
> compilation time or later on commandline). The memory is trimmed to 1/2 of detected
> physical memory (with minimum 128MB). (Otherwise OOM killer hits cryptsetup.)

and another quote from same post:

> If you read Argon2 RFC draft,
> https://datatracker.ietf.org/doc/draft-irtf-cfrg-argon2/ you can see this recommendation:
> 
> "Key derivation for hard-drive encryption, that takes 3 seconds on
> a 2 GHz CPU using 2 cores - Argon2id with 4 lanes and 6 GiB of RAM."

Personally I think that 128MB is more sane default than 1GB or 6GB (lol), just wanted to clarify this.
