### ISSUE TITLE
Move to a pure go implementation of Argon2id

### ISSUE THREAD

**Issue by josephlr** [google/fscrypt#82]
An implementation of Argon2id has [made it into x/crypto](https://go-review.googlesource.com/c/crypto/+/91935)!!!

We should switch over to this as it would get rid of any dependency on libargon2 and potentially increase performance. I'll post more perf info when I have a chance to prototype.

**Comment by josephlr** [comment]
Results of experimentation on my VirtualBox server (4 Processors, 8 GB RAM):

```bash
# Current C implementation using libargon2 (Argon2id)
$ fscrypt-c setup --force --verbose

Costs={time:1 memory:32 parallelism:4 }      -> 191.795µs
Costs={time:1 memory:64 parallelism:4 }      -> 132.099µs
Costs={time:1 memory:128 parallelism:4 }     -> 182.041µs
Costs={time:1 memory:256 parallelism:4 }     -> 179.475µs
Costs={time:1 memory:512 parallelism:4 }     -> 203.335µs
Costs={time:1 memory:1024 parallelism:4 }    -> 330.628µs
Costs={time:1 memory:2048 parallelism:4 }    -> 511.329µs
Costs={time:1 memory:4096 parallelism:4 }    -> 1.036409ms
Costs={time:1 memory:8192 parallelism:4 }    -> 1.888108ms
Costs={time:1 memory:16384 parallelism:4 }   -> 4.177142ms
Costs={time:1 memory:32768 parallelism:4 }   -> 8.306846ms
Costs={time:1 memory:65536 parallelism:4 }   -> 16.100146ms
Costs={time:1 memory:131072 parallelism:4 }  -> 33.159073ms
Costs={time:2 memory:131072 parallelism:4 }  -> 52.279717ms
Costs={time:4 memory:131072 parallelism:4 }  -> 90.485432ms
Costs={time:8 memory:131072 parallelism:4 }  -> 166.713871ms
Costs={time:16 memory:131072 parallelism:4 } -> 323.296062ms
Costs={time:32 memory:131072 parallelism:4 } -> 621.158755ms
Costs={time:64 memory:131072 parallelism:4 } -> 1.235619162s

# Potential go implementation using x/crypto/argon2.IDKey
$ fscrypt-pure setup --force --verbose

Costs={time:1 memory:32 parallelism:4 }      -> 150.407µs
Costs={time:1 memory:64 parallelism:4 }      -> 105.218µs
Costs={time:1 memory:128 parallelism:4 }     -> 237.461µs
Costs={time:1 memory:256 parallelism:4 }     -> 252.23µs
Costs={time:1 memory:512 parallelism:4 }     -> 701.503µs
Costs={time:1 memory:1024 parallelism:4 }    -> 1.511214ms
Costs={time:1 memory:2048 parallelism:4 }    -> 3.012162ms
Costs={time:1 memory:4096 parallelism:4 }    -> 4.604621ms
Costs={time:1 memory:8192 parallelism:4 }    -> 9.358836ms
Costs={time:1 memory:16384 parallelism:4 }   -> 22.028494ms
Costs={time:1 memory:32768 parallelism:4 }   -> 41.710244ms
Costs={time:1 memory:65536 parallelism:4 }   -> 81.355313ms
Costs={time:1 memory:131072 parallelism:4 }  -> 153.401565ms
Costs={time:2 memory:131072 parallelism:4 }  -> 177.53252ms
Costs={time:4 memory:131072 parallelism:4 }  -> 93.691733ms
Costs={time:8 memory:131072 parallelism:4 }  -> 185.729586ms
Costs={time:16 memory:131072 parallelism:4 } -> 365.324592ms
Costs={time:32 memory:131072 parallelism:4 } -> 720.697067ms
Costs={time:64 memory:131072 parallelism:4 } -> 1.440227683s
```

It seems like the Go version is slower and less consistent. Though, for ranges we care about, the go implementation is only 6%-16% slower. This means that users of the C implementation can have ~15% higher hashing costs, while staying within the time budget. This means that there is a bit of extra security in using the C implementation.

For example, on my machine, both of the following took about 1 second.

- C Implementation: Time=51, Memory=128MiB, Threads=4
- Go Implementation: Time=44, Memory=128MiB, Threads=4

I'll chat with @agl and @aead to see if there is an easy way to get performance parity.

**Comment by aead** [comment]
@josephlr 
The current Argon2 implementation uses SSE4.1 SIMD instructions while libargon2 (the official C/C++ reference implementation) can also take advantage of AVX2. The reason is that Go asm does not provide support for some AVX2 instructions - like multiplication (VPMULQ). 
As far as I know this will change with [Go1.10](https://tip.golang.org/doc/go1.10#asm). So I can provide a AVX2 implementation of the Argon2 core function without raw `BYTE` encoding. 

I cannot say whether it closes the performance gap for sure. However 6-16% sounds achievable - especially if you compare BLAKE2b SSE4.1 vs AVX2 performance. (The Argon2 core is very similar to a BLAKE2b round).

**Comment by aead** [comment]
@josephlr The AVX2 cl is pending. On my machines the performance improvement is about ~30-40% using Go1.10.
