### ISSUE TITLE
Passphrase is not updated when changing password with passwd

### ISSUE THREAD

**Issue by sebadoom** [google/fscrypt#94]
As I was looking into reproducing #93 in a VM I hit this bug.

Steps:
1. Setup PAM unlocking for ArchLinux as described in #77. Use login password.
2. Login as the user whose home is encrypted. Verify that the home is unlocked.
3. Use `passwd` to change that user's password.
4. Logout.
5. Log back in, confirm that the home directory is now unreadable.

VM: https://drive.google.com/open?id=1soLFKOoFHK47d31RCn6qmJB7AORe2ysg

Uncompress (using xz, no tarball) and launch using virt-manager. Fedora 26 settings. Two users: root and qemu, both have the same password: qemu. User qemu's home is encrypted, PAM unlocking is setup.

Edit: changing the passphrase manually to match the new login password using `fscrypt metadata` results in a working setup again.

**Comment by fancytenseletters** [comment]
Passwd on arch has its own config in `/etc/pam.d/passwd`. You have to add pam_fscrypt to that file.

**Comment by sebadoom** [comment]
Sigh, I wonder why Arch devs decided to do things this way. I'll test this and report back.

**Comment by fancytenseletters** [comment]
Or add `password	include		system-auth` line.

**Comment by fancytenseletters** [comment]
If you add `password include system-auth` to `passwd`, delete `pam_unix` from `/etc/pam.d/passwd` to not invoke it twice.

**Comment by sebadoom** [comment]
Adding `pam_fscrypt.so` to `/etc/pam.d/passwd` does not appear to work. Adding it before `pam_unix.so` results in a segfault using `passwd`. Adding it after results in a non-updated encryption password (locked home directory). Is this expected? I will now test the `system-auth` alternative.

**Comment by josephlr** [comment]
@sebadoom is `pam_fscrypt.so` even being triggered when you're calling `passwd`?

**Comment by ebiggers** [comment]
I've tested that on Arch Linux following the new guide https://wiki.archlinux.org/index.php/Fscrypt (and in particular the PAM configuration recommended there), running `passwd` updates login passphrase protected directories.  So this doesn't seem to be a valid issue anymore.  Closing.

**Comment by lnksz** [comment]
I hit this.
- Had a working setup with only `/home/user1` encrypted with fscrypt using the login protector
- Updated `pam.d` files as described in the arch wiki (wiki was updated since I set up the pam login originally)
- Change the password with `passw`
- On next login after a successful login, the GDM jumped back to the login page without showing the desktop
- I had to manually update the passphrase for the protector `fscrypt metadata change-passphrase --protector=/:aabbccddeeff...` (protector from `fscrypt setup /home/user1`)

**Comment by ebiggers** [comment]
@lnksz can you please file a new issue?  This one was closed 3 years ago so is unlikely to be related.  Please include full details, e.g. which Linux distro you are using, whether you ran `passwd` as a user or as root, and the log from the `passwd` operation after adding the `debug` option to `pam_fscrypt.so`.

**Comment by lnksz** [comment]
Thank you @ebiggers for such a prompt response! After re-checking, I have one question to see whether it is a bug at all and so would be worth an own ticket:

I repeated the password change after checking again that the files are as the Arch Doc described.

I noticed that if I try to issue `fscrypt metadata change-passphrase --protector=/:1b4e0ffd3fb1c...` as the non-root user, for which the login protector is used to protect it's /home/ directory.
```
sudo -u user1 fscrypt metadata change-passphrase --protector=/:1b4e0ffd3fb1c04a
Enter old login passphrase for user1: 
Enter new login passphrase for user1: 
[ERROR] fscrypt metadata change-passphrase: rename /.fscrypt/protectors/.tmp3864838124
                                            /.fscrypt/protectors/1b4e0ffd3fb1c04a: operation not permitted
```
So user1 cannot change files in `/.fscrypt`, which belongs to root. But that should belong to root, right? At least here the [example](https://github.com/google/fscrypt#example-usage) uses `sudo fscrypt setup` as well.

So my question is, how could a `passwd` issued as non-root change that file?

There is also an `/home/.fscrypt` but there only a "link" protector `/home/.fscrypt/protectors/1b4e0ffd3fb1c04a.link`

Does this look like a messed-up setup? Or is it something worth opening a ticket for?

**Comment by ebiggers** [comment]
You are probably running into https://github.com/google/fscrypt/issues/319, which was already fixed but only for new protectors.  You can fix it for your existing protector file by making it owned by your user: `sudo chown $USER:$USER /.fscrypt/protectors/1b4e0ffd3fb1c04a`

> user1 cannot change files in /.fscrypt, which belongs to root.

It can either be root-writable only, or world-writable with the sticky bit like `/tmp`, depending on how you set it up originally.  See https://github.com/google/fscrypt#setting-up-fscrypt-on-a-filesystem.  Anyway, I don't think that's relevant here.  The current design is that even if the metadata directory is root-writable, login protectors are made owned by the user, which allows the user to overwrite them.  Just fix the owner of your login protector file, and you should be good to go.

**Comment by lnksz** [comment]
Thank you for your response, this makes also sense, since I set up fscrypt for this user/dir quite some years ago.

I appreciate your helpfulness and thank you for maintaining this great tool!
